[package]
categories = ["development-tools::ffi"]
description = "Sub-optimal language binding generator"
edition = "2018"
name = "riko"
repository = "https://github.com/seamlik/riko"
version = "0.0.1"

[lib]
proc-macro = true

[dependencies]
quote = "1"
syn = "1"