[package]
authors = ["殷啟聰 | Kai-Chung Yan <seamlik@debian.org>"]
categories = ["development-tools::ffi"]
description = "Core components of Riko"
edition = "2018"
name = "riko_core"
repository = "https://github.com/seamlik/riko"
version = "0.0.1"

[dependencies]
anyhow = "1"
blake2 = "0"
data-encoding = "2"
itertools = "0"
proc-macro2 = "1"
quote = "1"
regex = { version = "1", features = ["pattern"] }
syn = { version = "1", features = ["full"] }