[package]
edition = "2018"
name = "samples"
publish = false
version = "0.0.1"

[lib]
crate-type = ["cdylib"]

[dependencies]
jni = "0.13.1"
once_cell = "1"
riko = { path = "../../macros" }
riko_runtime = { path = "../../runtime-rust" }
serde = { version = "1.0.98", features = ["derive"] }