[package]
edition = "2018"
name = "examples"
publish = false
version = "0.0.1"

[lib]
crate-type = ["cdylib"]

[dependencies]
riko = { path = "../macros" }
riko_runtime = { path = "../runtime-rust" }
serde = { version = "1.0.98", features = ["derive"] }