on:
  push:
    branches:
      - master
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          default: true
          profile: minimal
          toolchain: nightly
      - run: cargo run --package riko --release
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: gradle sonarqube
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}