name: Verify
on: [push, pull_request]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ github.sha }}
          restore-keys: ${{ runner.os }}-gradle
      - uses: actions-rs/toolchain@v1
        with:
          components: rustfmt, clippy
          default: true
          profile: minimal
          toolchain: nightly
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: make verify
      - uses: actions-rs/clippy-check@v1
        with:
          args: --all-features
          token: ${{ secrets.GITHUB_TOKEN }}